@echo off
setlocal enabledelayedexpansion
title CH32V003 - Generate .clangd

:: ============================================================
::  make_clangd.bat
::  Auto-generate .clangd สำหรับ clangd language server
::  รัน script นี้ใน root ของ project เพื่อสร้าง .clangd ใหม่
::
::  Usage: .\make_clangd.bat
:: ============================================================

set "PROJECT_ROOT=%~dp0"
set "PROJECT_ROOT=%PROJECT_ROOT:~0,-1%"

echo.
echo =============================================================
echo   Generate .clangd for clangd Language Server
echo   Project: %PROJECT_ROOT%
echo =============================================================
echo.

:: ============================================================
::  Auto-detect Toolchain (prefer GCC12)
:: ============================================================
set "TOOLCHAIN_BASE=C:\MounRiver\MounRiver_Studio2\resources\app\resources\win32\components\WCH\Toolchain"

set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC12"
set "GCC_TUPLE=riscv-wch-elf"
set "GCC_VER=12.2.0"
set "TC_LABEL=RISC-V Embedded GCC12"

if not exist "%TC_DIR%\bin\%GCC_TUPLE%-gcc.exe" (
    set "TC_DIR=%TOOLCHAIN_BASE%\RISC-V Embedded GCC"
    set "GCC_TUPLE=riscv-none-embed"
    set "GCC_VER=8.2.0"
    set "TC_LABEL=RISC-V Embedded GCC"
)

if not exist "%TC_DIR%\bin\%GCC_TUPLE%-gcc.exe" (
    echo [ERROR] ไม่พบ MounRiver toolchain ที่:
    echo         %TOOLCHAIN_BASE%
    echo   กรุณาตรวจสอบว่าติดตั้ง MounRiver Studio 2 แล้ว
    goto :FAIL
)
echo [OK] Toolchain : %TC_LABEL%
echo [OK] Compiler  : %GCC_TUPLE%-gcc.exe

:: แปลง path เป็น forward slash
set "TC_DIR_FWD=%TC_DIR:\=/%"
set "PROJECT_FWD=%PROJECT_ROOT:\=/%"

:: ============================================================
::  Scan Project Include Directories
:: ============================================================
echo.
echo --- Scanning project include directories ---

set "OUT=%PROJECT_ROOT%\.clangd"

:: เขียนส่วน header ของ .clangd
(
echo # ============================================================
echo #  .clangd - auto-generated by make_clangd.bat
echo #  Project  : %PROJECT_FWD%
echo #  Toolchain: %TC_LABEL% ^(%GCC_TUPLE%-gcc^)
echo #  Generated: %DATE% %TIME%
echo #  Re-run make_clangd.bat เพื่ออัปเดตเมื่อ project structure เปลี่ยน
echo # ============================================================
echo.
echo CompileFlags:
echo   Compiler: "%TC_DIR_FWD%/bin/%GCC_TUPLE%-gcc.exe"
echo.
echo   Add:
echo     # Force RISC-V 32-bit target - แก้ "interrupt attribute" x86-64 error
echo     - "--target=riscv32-unknown-elf"
echo.
echo     # Force C language for .h files - แก้ ObjC++ false detection
echo     - "-x"
echo     - "c"
echo.
echo     # C Standard
echo     - "-std=gnu99"
echo.
echo     # GCC system includes - แก้ "stdio.h file not found"
echo     - "-I%TC_DIR_FWD%/%GCC_TUPLE%/include"
echo     - "-I%TC_DIR_FWD%/lib/gcc/%GCC_TUPLE%/%GCC_VER%/include"
echo     - "-I%TC_DIR_FWD%/lib/gcc/%GCC_TUPLE%/%GCC_VER%/include-fixed"
echo.
echo     # Project include paths ^(auto-detected^)
) > "%OUT%"

:: เพิ่ม include paths ของ project
call :ADD_INC "Debug"
call :ADD_INC "Core"
call :ADD_INC "Peripheral\inc"
call :ADD_INC "User"
call :ADD_INC "User\hardware"

:: สแกน User\Lib แบบ recursive (ถ้ามี)
if exist "%PROJECT_ROOT%\User\Lib" (
    for /d /r "%PROJECT_ROOT%\User\Lib" %%D in (*) do (
        set "D=%%~fD"
        set "D=!D:\=/!"
        echo     - "-I!D!">> "%OUT%"
        echo   [+] %%~fD
    )
    :: เพิ่ม User\Lib root ด้วย
    call :ADD_INC "User\Lib"
)

:: เขียนส่วนที่เหลือ
(
echo.
echo     # Preprocessor Defines
echo     - "-D_DEBUG"
echo     - "-DCH32V00x"
echo     - "-DCH32V003"
echo.
echo     # Suppress false-positive warnings สำหรับ embedded C
echo     - "-Wno-implicit-function-declaration"
echo     - "-Wno-int-conversion"
echo     - "-Wno-incompatible-pointer-types"
echo     - "-Wno-attributes"
echo.
echo   Remove:
echo     # ตัด RISC-V / WCH-specific flags ที่ clangd ไม่รู้จัก
echo     - "-march=rv32ecxw"
echo     - "-march=rv32ec"
echo     - "-mabi=ilp32e"
echo     - "-msmall-data-limit=*"
echo     - "-msave-restore"
echo     - "-fmessage-length=*"
echo     - "-fno-common"
echo     - "-nostartfiles"
echo     - "-Xlinker"
echo     - "--gc-sections"
echo     - "--specs=*"
echo     - "-lprintf"
echo.
echo Diagnostics:
echo   UnusedIncludes: None
echo   ClangTidy:
echo     Remove:
echo       - "modernize-*"
echo       - "cppcoreguidelines-*"
echo       - "readability-*"
echo       - "performance-*"
echo       - "bugprone-reserved-identifier"
echo       - "cert-dcl37-c"
echo       - "cert-dcl51-cpp"
echo.
echo Index:
echo   Background: Build
) >> "%OUT%"

echo.
echo =============================================================
echo   [OK] Created: .clangd
echo.
echo   กด Ctrl+Shift+P ใน VS Code แล้วเลือก:
echo     "clangd: Restart Language Server"
echo =============================================================
echo.
goto :EOF


:: ============================================================
::  Subroutine: ADD_INC "relative\path"
::  เพิ่ม include path ถ้า directory นั้นมีอยู่จริง
:: ============================================================
:ADD_INC
    set "DIR=%PROJECT_ROOT%\%~1"
    if exist "%DIR%" (
        set "DIR_FWD=%DIR:\=/%"
        echo     - "-I!DIR_FWD!">> "%OUT%"
        echo   [+] %~1
    )
    exit /b 0


:FAIL
echo.
echo =============================================================
echo   [ERROR] Failed to generate .clangd
echo =============================================================
echo.
exit /b 1
